question_data = [
    {"text": "FTP", "answer": "20/21"},
    {"text": "SSH", "answer": "22"},
    {"text": "Telnet", "answer": "23"},
    {"text": "SMTP", "answer": "25"},
    {"text": "DNS", "answer": "53"},
    {"text": "DHCP", "answer": "67/68"},
    {"text": "HTTP", "answer": "80"},
    {"text": "POP3", "answer": "110"},
    {"text": "NetBIOS/NetBT", "answer": "137/139"},
    {"text": "IMAP", "answer": "143"},
    {"text": "SNMP", "answer": "161/162"},
    {"text": "LDAP", "answer": "389"},
    {"text": "HTTPS", "answer": "443"},
    {"text": "SMB/CIFS", "answer": "445"},
    {"text": "RDP", "answer": "3389"},
    {"text": "TFTP", "answer": "69"},
]
